
export const movies = [
    {
        Movie: "",
        Thumbnail: "/images/tit.png",
        Scene: "/images/titanicScene.png",
        Logo: "/images/movieLogo.png",
        Name: "Titanic",
        Description:
            "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "https://ipfs.moralis.io:2053/ipfs/QmNtxfy9Mk8qLsdGnraHGk5XDim8ayR93krM24ETJEd2bG/media/0",
        Thumbnail: "/images/spidey.png",
        Scene: "/images/spideyScene.png",
        Logo: "/images/spideyLogo.png",
        Name: "Spiderman Homecoming",
        Description: "Peter Parker tries to stop the Vulture from selling weapons made with advanced Chitauri technology while trying to balance his life as an ordinary high school student.",
        Genre: "Action, Superhero, Comedy",
        Actors: "Tom Holland, Zendeya",
        Year: "2017",
        Duration: "2h 13min",
    },
    {
        Movie: "",
        Thumbnail: "/images/jumanji.png",
        Scene: "",
        Logo: "",
        Name: "Jumanji",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "",
    },
    {
        Movie: "https://ipfs.moralis.io:2053/ipfs/QmWWnyCZwh8RVnamjeLhGmpYM2C3oDr3FzF7zgv5ur24z5/media/0",
        Thumbnail: "/images/moralis.png",
        Scene: "/images/moralisScene.png",
        Logo: "/images/moralisLogo.png",
        Name: "Moralis Rap",
        Description: "Moralis serverless Web3 Dapps, is a beautiful music video that tells a touching story of how anyone can become a Web3 developer if they put their trust in the hands of the musically gifted team at Moralis. ",
        Genre: "Music Video",
        Actors: "Ivan Liljeqvist, Filip Martinsson, CTO Larsson",
        Year: "2021",
        Duration: "1min 2sec",
    },
    {
        Movie: "",
        Thumbnail: "/images/wolf.png",
        Scene: "",
        Logo: "",
        Name: "Wolf Of Wallstreet",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "",
    },
    {
        Movie: "",
        Thumbnail: "/images/mrs.png",
        Scene: "",
        Logo: "",
        Name: "Mr and Mrs Smith",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "",
    },
    {
        Movie: "",
        Thumbnail: "/images/hob.png",
        Scene: "",
        Logo: "",
        Name: "Hobbit",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "",
    },
    {
        Movie: "",
        Thumbnail: "/images/shrek.png",
        Scene: "",
        Logo: "",
        Name: "",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "",
    },
    {
        Movie: "",
        Thumbnail: "/images/reven.png",
        Scene: "",
        Logo: "",
        Name: "",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "",
    },
    {
        Movie: "",
        Thumbnail: "/images/imit.png",
        Scene: "",
        Logo: "",
        Name: "",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "",
    }
];
